name: flutter_project
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State management
  provider: ^6.1.2

  # Navigation
  go_router: ^14.2.0

  # HTTP client
  dio: ^5.5.0

  # Local DB (Drift + sqlite)
  drift: ^2.18.0
  sqlite3_flutter_libs: ^0.5.0

  # Dependency injection
  get_it: ^7.6.7

  # For database file path
  path: ^1.9.0
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  drift_dev: ^2.18.0
  build_runner: ^2.4.12

flutter:
  uses-material-design: true
